import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Plus,RefreshCw,Pencil,Search,X,CalendarDays,Wallet,Users} from 'lucide-react';
import {clientApi,clientError} from './ClientWorkspace';
import './ClientRecords.css';
interface Row {status?:string;id:number;name:string;lastName:string;category:string;description:string;amount:number;date:string;phone:string;location:string;startTime:string;endTime:string|null;paymentMethod?:string;referenceNumber?:string}
const expenseCategories=['UTILITIES','SUPPLIES','SALARY','MINISTRY','MAINTENANCE','TRANSPORTATION','FOOD','OTHER'];
const incomeCategories=['SUNDAY WORSHIP TOTAL INCOME','DONATION','EVENT','BOOKS','MERCHANDISE','REGISTRATION','OTHER'];
const eventTypes=['Evangelism','Leadership Meeting','Food Reservation','Conference','Seminar','Outreach','Fun Run','Camp','Fellowship','Concert','Training','Community Event','Other'];
const methods=['CASH','BANK TRANSFER','GCASH','CHECK','CARD','OTHER'];
const day=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const options=(values:string[],current?:string)=>[...new Set([...(current&&!values.includes(current)?[current]:[]),...values])].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>);
export default function ClientRecords({kind,title,canCreate,canEdit,canDelete}:{kind:string;title:string;canCreate:boolean;canEdit:boolean;canDelete:boolean}) {
 const [rows,setRows]=useState<Row[]>([]),[form,setForm]=useState<Row|null>(null),[skip,setSkip]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState('');
 const lock=useRef(false),generation=useRef(0),dialog=useRef<HTMLDialogElement>(null);
 const financial=kind==='income'||kind==='expenses',event=kind==='events',visitor=kind==='visitors';
 const singular=event?'event':visitor?'visitor':kind==='ministries'?'ministry':kind==='expenses'?'expense':'income entry';
 const categories=kind==='expenses'?expenseCategories:incomeCategories;
 const statuses=event?['SCHEDULED','ONGOING','COMPLETED','CANCELLED']:['ACTIVE','INACTIVE'];
 async function load(signal?:AbortSignal){const version=++generation.current;const r=await clientApi.get<Row[]>(`/records/${kind}`,{params:{skip},signal});if(!Array.isArray(r.data))throw new Error('Invalid response');if(version===generation.current&&!signal?.aborted)setRows(r.data);}
 useEffect(()=>{const c=new AbortController();setBusy(true);setError('');void load(c.signal).catch(e=>{if(!c.signal.aborted)setError(clientError(e));}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>{c.abort();generation.current++;};},[kind,skip]);
 useEffect(()=>{if(!form)return;const previous=document.activeElement;dialog.current?.showModal();return()=>{if(previous instanceof HTMLElement)previous.focus();};},[!!form]);
 async function run(task:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');try{await task();}catch(e){setError(clientError(e));}finally{lock.current=false;setBusy(false);}}
 function create(){setError('');setForm({id:0,name:financial?categories[0]:'',lastName:'',category:event?'Conference':'OTHER',description:'',amount:0,date:day(),phone:'',location:'',startTime:'09:00:00',endTime:null,status:event?'SCHEDULED':'ACTIVE',paymentMethod:'CASH',referenceNumber:''});}
 const visible=rows.filter(r=>`${r.name} ${r.lastName} ${r.category} ${r.description} ${r.location}`.toLowerCase().includes(search.toLowerCase()));
 async function save(){if(!form)return;const time=(v?:string|null)=>v?.length===5?v+':00':v;const payload={...form,date:form.date.slice(0,10),startTime:time(form.startTime)||'00:00:00',endTime:time(form.endTime)||null,status:financial?undefined:form.status};
   await run(async()=>{const result=form.id?await clientApi.put(`/records/${kind}/${form.id}`,payload):await clientApi.post(`/records/${kind}`,payload);setForm(null);setMessage(result.data.message||'Saved successfully.');try{await load();}catch(e){setError('Saved successfully, but the list could not refresh. Do not submit again. '+clientError(e));}});
 }
 const field=(key:keyof Row,label:string,type='text',required=false,maxLength=100)=><label>{label}<input type={type} required={required} maxLength={maxLength} value={String(form?.[key]??'').slice(0,type==='date'?10:undefined)} onChange={e=>setForm(f=>f?{...f,[key]:e.target.value}:f)}/></label>;
 return <section className="client-records">
  <header className="cr-header"><div className="cr-heading"><span className="cr-icon">{financial?<Wallet/>:event?<CalendarDays/>:<Users/>}</span><div><h2>{title} Management</h2><p>{financial?'Track church finances with clear categories and payment details.':event?'Plan church events and manage their schedules.':'Manage your church directory and contact information.'}</p></div></div><div className="cr-actions"><button className="cr-secondary" disabled={busy} onClick={()=>void run(()=>load())}><RefreshCw size={16}/> Refresh</button>{canCreate&&<button disabled={busy} onClick={create}><Plus size={16}/> Add {singular}</button>}</div></header>
  {!form&&error&&<div className="cr-alert" role="alert">{error}</div>}{message&&<div className="cr-success" role="status">{message}</div>}
  <div className="cr-overview"><article><span>Records on this page</span><strong>{rows.length}</strong></article><article><span>{financial?'Total on this page':'Active / scheduled on this page'}</span><strong>{financial?rows.reduce((n,r)=>n+r.amount,0).toLocaleString(undefined,{minimumFractionDigits:2}):rows.filter(r=>!['INACTIVE','CANCELLED','COMPLETED'].includes(r.status||'')).length}</strong></article></div>
  <div className="cr-table-card"><div className="cr-toolbar"><h3>{title} records</h3><label className="cr-search"><Search size={16}/><input aria-label="Search this page" placeholder="Search this page…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
  <div className="cr-scroll"><table><thead><tr><th>{financial?'Category':visitor?'Visitor':event?'Event':'Ministry'}</th>{financial?<><th>Date</th><th>Amount</th><th>Payment</th></>:event?<><th>Date & time</th><th>Venue</th><th>Status</th></>:<><th>Contact / location</th><th>Status</th></>}<th>Actions</th></tr></thead><tbody>
  {visible.map(r=><tr key={r.id}><td><strong>{r.name} {r.lastName}</strong><span className="cr-detail">{event?r.category:r.description}</span></td>{financial?<><td>{r.date.slice(0,10)}</td><td className="cr-amount">{r.amount.toLocaleString(undefined,{minimumFractionDigits:2})}</td><td>{r.paymentMethod||'—'}<span className="cr-detail">{r.referenceNumber}</span></td></>:event?<><td>{r.date.slice(0,10)}<span className="cr-detail">{r.startTime.slice(0,5)}{r.endTime?' – '+r.endTime.slice(0,5):''}</span></td><td>{r.location||'—'}</td><td><span className="cr-badge">{r.status}</span></td></>:<><td>{r.phone||'—'}<span className="cr-detail">{r.location}</span></td><td><span className="cr-badge">{r.status}</span></td></>}<td><div className="cr-row-actions">{canEdit&&<button className="cr-secondary" disabled={busy} onClick={()=>{setError('');setForm({...r,paymentMethod:r.paymentMethod||'CASH'});}}><Pencil size={14}/> Edit</button>}{canDelete&&<button className="cr-danger" disabled={busy||(!financial&&['INACTIVE','CANCELLED'].includes(r.status||''))} onClick={()=>{if(window.confirm(financial?'Delete this financial record?':event?'Cancel this event? Attendance history is retained.':'Make this record inactive? History is retained.'))void run(async()=>{const result=await clientApi.delete(`/records/${kind}/${r.id}`);setMessage(result.data.message);await load();});}}>{financial?'Delete':event?'Cancel event':'Deactivate'}</button>}</div></td></tr>)}
  {!visible.length&&<tr><td colSpan={6} className="cr-empty">{busy?'Loading records…':error?'Records unavailable. Use Refresh to retry.':search?'No matching records on this page.':`No ${title.toLowerCase()} recorded yet.`}</td></tr>}</tbody></table></div>
  <footer className="cr-pagination"><span>Page {skip/50+1} · {visible.length} shown</span><div><button className="cr-secondary" disabled={busy||skip===0} onClick={()=>{setSearch('');setSkip(n=>Math.max(0,n-50));}}>Previous</button><button className="cr-secondary" disabled={busy||rows.length<50} onClick={()=>{setSearch('');setSkip(n=>n+50);}}>Next</button></div></footer></div>
  {form&&createPortal(<dialog ref={dialog} className="cr-dialog client-records" onCancel={e=>{e.preventDefault();if(!busy)setForm(null);}}><header className="cr-dialog-header"><div><h2>{form.id?'Edit':'Add'} {singular}</h2><p>Enter the details below.</p></div><button className="cr-secondary" aria-label="Close form" disabled={busy} onClick={()=>setForm(null)}><X size={18}/></button></header>{error&&<div className="cr-alert" role="alert">{error}</div>}
  <form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy} className="cr-form-grid">
  {financial?<label>Category<select aria-label="Category" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}>{options(categories,form.name)}</select></label>:field('name',visitor?'First name':event?'Event title':'Ministry name','text',true)}
  {visitor&&field('lastName','Last name','text',true)}
  {event&&<label>Event type<select aria-label="Event type" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{options(eventTypes,form.category)}</select></label>}
  {kind!=='ministries'&&field('date',event?'Event date':visitor?'First visit date':'Date','date',true)}
  {financial&&<><label>Amount<input type="number" min="0" max="999999999999.99" step="0.01" required value={form.amount} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/></label><label>Payment method<select aria-label="Payment method" value={form.paymentMethod||'CASH'} onChange={e=>setForm({...form,paymentMethod:e.target.value})}>{options(methods,form.paymentMethod)}</select></label>{field('referenceNumber','Reference number')}</>}
  {event&&<>{field('startTime','Start time','time',true)}{field('endTime','End time','time')}</>}
  {!financial&&<>{field('location',event?'Venue':visitor?'Address':'Meeting location','text',false,150)}{!event&&field('phone','Contact number','tel',false,20)}<label>Status<select aria-label="Status" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{options(statuses,form.status)}</select></label></>}
  <label className="cr-full">Description / notes<textarea rows={3} maxLength={kind==='income'?250:500} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>
  </fieldset><footer className="cr-form-footer"><button type="button" className="cr-secondary" disabled={busy} onClick={()=>setForm(null)}>Cancel</button><button disabled={busy} type="submit">{busy?'Saving…':form.id?'Update '+singular:'Save '+singular}</button></footer></form></dialog>,document.body)}
 </section>;
}
